# Generated by Django 5.1.1 on 2024-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Author/ผู้แต่ง'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Book/หนังสือ'},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'ordering': ['id'], 'verbose_name_plural': 'Book Comment/ความคิดเห็น'},
        ),
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagory/หมวดหมู่'},
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('M', 'Medium'), ('A', 'Advance')], max_length=5, null=True),
        ),
    ]
