# Generated by Django 5.1.1 on 2024-10-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='quota_open',
            new_name='is_quota_open',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='seats_available',
            new_name='seats',
        ),
        migrations.DeleteModel(
            name='QuotaRequest',
        ),
    ]
