name: Testing

on: push
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install coverage
    - name: Run Tests
      working-directory: registrar
      run: |
         python manage.py makemigrations
         python manage.py migrate
         coverage run --source='.' manage.py test
         coverage report
